spring:
  application:
    name: AI Demo Project
  ai:
    ollama:
      base-url: https://897194260c24.ngrok-free.app
      chat:
        options:
          model: llama3
          temperature: 0.7  # setting creativity level of the model
